import {
  Moon,
  Salad,
  Dumbbell,
  HeartPulse,
  Footprints,
  StretchHorizontal,
  WineOff,
  Target,
  Baby,
  House,
  Sunrise,
  Sunset,
  Smile,
  GlassWater,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  sleep: Moon,
  protein: Salad,
  weightTraining: Dumbbell,
  cardio: HeartPulse,
  steps: Footprints,
  stretching: StretchHorizontal,
  healthyEating: Salad,
  noAlcohol: WineOff,
  primaryGoal: Target,
  helpedWifeExercise: Baby,
  householdHelp: House,
  wakeTime: Sunrise,
  bedTime: Sunset,
  oralHygiene: Smile,
  goal: Target,
  water: GlassWater,
};

export const ICON_LABELS: Record<string, string> = {
  sleep: "Sleep",
  protein: "Protein",
  weightTraining: "Workout",
  cardio: "Cardio",
  steps: "Steps",
  stretching: "Stretching",
  healthyEating: "Healthy Eating",
  noAlcohol: "No Alcohol",
  primaryGoal: "Goal",
  helpedWifeExercise: "Family",
  householdHelp: "House",
  wakeTime: "Wake Time",
  bedTime: "Bed Time",
  oralHygiene: "Oral Hygiene",
  goal: "General Goal",
  water: "Water intake",
};
